"use strict";

export const tasks = [
  { tarea: "🛋️ Sofá", prioridad: 3 },
  { tarea: "🛏️ Cama", prioridad: 5 },
  { tarea: "🪑 Silla", prioridad: 2 },
  { tarea: "🍽️ Mesa", prioridad: 4 },
  { tarea: "🖥️ Ordenador", prioridad: 7 },
  { tarea: "📺 Televisión", prioridad: 6 },
  { tarea: "🖨️ Impresora", prioridad: 2 },
  { tarea: "📱 Teléfono móvil", prioridad: 9 },
  { tarea: "🧳 Maletero", prioridad: 8 },
  { tarea: "💡 Lámpara", prioridad: 1 },
  { tarea: "🖼️ Cuadro", prioridad: 3 },
  { tarea: "🚪 Puerta", prioridad: 4 },
  { tarea: "🪟 Ventana", prioridad: 6 },
  { tarea: "🛁 Bañera", prioridad: 5 },
  { tarea: "🚿 Ducha", prioridad: 4 },
  { tarea: "🧴 Jabón", prioridad: 3 },
  { tarea: "🧺 Cesta de ropa", prioridad: 8 },
  { tarea: "🧹 Escoba", prioridad: 2 },
  { tarea: "🧽 Esponja", prioridad: 1 },
  { tarea: "🍴 Platos", prioridad: 3 },
  { tarea: "🥄 Cucharas", prioridad: 2 },
  { tarea: "🍷 Copas", prioridad: 7 },
  { tarea: "📚 Libros", prioridad: 6 },
  { tarea: "🧸 Peluche", prioridad: 1 },
  { tarea: "🧯 Extintor", prioridad: 5 },
  { tarea: "💻 Portátil", prioridad: 9 },
  { tarea: "🗑️ Basura", prioridad: 4 },
  { tarea: "🧰 Herramientas", prioridad: 6 },
  { tarea: "🧳 Maleta", prioridad: 2 },
  { tarea: "🎧 Auriculares", prioridad: 3 },
  { tarea: "🪞 Espejo", prioridad: 8 },
  { tarea: "🚽 Inodoro", prioridad: 5 }
];
